import '../globals.css';

import { Separator } from '@radix-ui/react-separator';
import { Metadata } from 'next';
import { redirect } from 'next/navigation';

import { logout } from '@/app/actions/auth';
import { InvoiceProvider } from '@/app/context/invoice-context';
import { AppSidebar } from '@/components/app-sidebar';
import Footer from '@/components/footer';
import { Button } from '@/components/ui/button';
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { getSession } from '@/lib/session';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  if (!session) {
    redirect('/login');
  }

  return (
    <InvoiceProvider>
      <SidebarProvider>
        <AppSidebar session={session} />
        <SidebarInset className="min-w-0">
          <header className="sticky top-0 z-10 flex bg-sidebar h-16 shrink-0 items-center gap-2 border-b transition-[width,height] ease-linear">
            <div className="flex items-center justify-between w-full px-4">
              <div className="flex items-center gap-2">
                <SidebarTrigger className="-ml-1 text-sidebar-foreground cursor-pointer" />
                <Separator orientation="vertical" className="mr-2 data-[orientation=vertical]:h-6" />
              </div>
              <div className="flex items-center gap-2">
                <Button variant="destructive" onClick={logout}>
                  Logout
                </Button>
              </div>
            </div>
          </header>
          <main className="flex-1 min-w-0">{children}</main>
          <Footer />
        </SidebarInset>
      </SidebarProvider>
    </InvoiceProvider>
  );
}
